name: 'Setup runner'
description: 'It setups pnpm, node and installs dependencies'
runs:
  using: composite
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 10
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 24
        cache: pnpm
    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile --ignore-scripts
